name: Tests
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              uses: php-actions/composer@v5
              with:
                  php_version: 7.4
            - name: Run tests
              uses: php-actions/phpunit@v2
              with:
                  php_version: 7.4
